"""Reference labour role profiles keyed by work type.

This module captures curated role data for Sri Lankan construction
scenarios so that the predictor can fall back to realistic crews even
when labour roles are not explicitly referenced in the BOQ text.
"""

from __future__ import annotations

from typing import Dict, List

# Each work type may define the keywords that indicate a match as well
# as the structured role catalogue that should be surfaced in reports.
# We now also expose recommended vehicle and machinery mixes so that
# downstream layers can build fleet plans and fuel projections.
WORK_TYPE_LABOUR_PROFILES: Dict[str, Dict[str, List[dict]]] = {
    "wall_construction": {
        "keywords": [
            "build a wall",
            "boundary wall",
            "block wall",
            "brick wall",
            "masonry wall",
            "partition wall",
            "retaining wall",
        ],
        "fallback_tokens": ["wall"],
        "roles": [
            {
                "slug": "general_labourer",
                "english": "General Labourer",
                "sinhala": "කම්කරු",
                "skill_level": "unskilled",
                "daily_rate_lkr": {"min": 3500, "max": 4800},
                "responsibilities": "Carrying bricks/blocks, mixing mortar, cleaning work areas, basic backfilling",
                "typical_count": {"min": 4, "max": 8},
            },
            {
                "slug": "helper",
                "english": "Helper / Assistant Labourer",
                "sinhala": "උපකාරක",
                "skill_level": "unskilled",
                "daily_rate_lkr": {"min": 3800, "max": 5000},
                "responsibilities": "Assist masons, shuttle materials, clear debris, maintain small tools",
                "typical_count": {"min": 3, "max": 6},
            },
            {
                "slug": "material_carrier",
                "english": "Material Carrier",
                "sinhala": "බර ගෙනියන කම්කරු",
                "skill_level": "unskilled",
                "daily_rate_lkr": {"min": 3500, "max": 4500},
                "responsibilities": "Transport sand, cement bags and bricks from laydown areas to the line of work",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "assistant_mason",
                "english": "Assistant Mason",
                "sinhala": "බ්ලොක් බෙන්ඩිං උපකාරක",
                "skill_level": "semi-skilled",
                "daily_rate_lkr": {"min": 4800, "max": 6500},
                "responsibilities": "Lay basic blocks, prepare mortar, help with alignment and pointing",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "bar_bender_assistant",
                "english": "Bar Bender Assistant",
                "sinhala": "බාර් බෙන්ඩිං උපකාරක",
                "skill_level": "semi-skilled",
                "daily_rate_lkr": {"min": 5000, "max": 6800},
                "responsibilities": "Cut and bend reinforcement for columns, ring beams and pilasters",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "plaster_assistant",
                "english": "Plaster Assistant",
                "sinhala": "ප්ලාස්ටර් උපකාරක",
                "skill_level": "semi-skilled",
                "daily_rate_lkr": {"min": 5000, "max": 6500},
                "responsibilities": "Prepare plaster mixes, apply base coats, clean trowels and hawks",
                "typical_count": {"min": 1, "max": 3},
            },
            {
                "slug": "mason",
                "english": "Mason / Bricklayer",
                "sinhala": "මේසන්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 6500, "max": 9500},
                "responsibilities": "Lay bricks/blocks plumb and level, set string lines, ensure bonding",
                "typical_count": {"min": 3, "max": 6},
            },
            {
                "slug": "block_mason",
                "english": "Block Mason",
                "sinhala": "බ්ලොක් මේසන්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 6000, "max": 8500},
                "responsibilities": "Specialise in cement block walls and faster production runs",
                "typical_count": {"min": 2, "max": 5},
            },
            {
                "slug": "bar_bender",
                "english": "Bar Bender / Steel Fixer",
                "sinhala": "බාර් බෙන්ඩර්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7000, "max": 10000},
                "responsibilities": "Fix reinforcement cages for columns, lintels and ring beams",
                "typical_count": {"min": 1, "max": 3},
            },
            {
                "slug": "welder",
                "english": "Welder",
                "sinhala": "වෙල්ඩර්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7500, "max": 11000},
                "responsibilities": "Fabricate or tie-in steel frames, grills or custom reinforcement",
                "typical_count": {"min": 0, "max": 1},
            },
            {
                "slug": "foreman",
                "english": "Foreman / Site Mason Supervisor",
                "sinhala": "ෆෝමන්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 10000, "max": 15000},
                "responsibilities": "Supervise crews, verify alignment, manage day plans and QA",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "site_engineer",
                "english": "Site Engineer / Quantity Surveyor",
                "sinhala": "සයිට් ඉංජිනේරු",
                "skill_level": "professional",
                "daily_rate_lkr": {"min": 15000, "max": 35000},
                "responsibilities": "Check drawings, measure progress, certify BOQs and ensure compliance",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "safety_officer",
                "english": "Safety Officer",
                "sinhala": "සුරක්ෂිතතා නිලධාරී",
                "skill_level": "professional",
                "daily_rate_lkr": {"min": 12000, "max": 20000},
                "responsibilities": "Monitor scaffolding, PPE usage and fall protection measures",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "driver",
                "english": "Driver (Material Logistics)",
                "sinhala": "රියදුරු",
                "skill_level": "support",
                "daily_rate_lkr": {"min": 5000, "max": 8000},
                "responsibilities": "Deliver bricks, sand and cement to site using trucks or tractors",
                "typical_count": {"min": 1, "max": 2},
            },
        ],
        "vehicles": [
            {
                "slug": "tipper_truck",
                "name": "Tipper Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 45,
                "usage": "Haul sand, aggregates and dispose spoil",
                "typical_count": {"min": 1, "max": 3},
            },
            {
                "slug": "small_truck",
                "name": "Small Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 22,
                "usage": "Deliver bricks, blocks and bagged cement",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "pickup_truck",
                "name": "Pickup Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 18,
                "usage": "Supervisor mobility and light cargo",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
        "machinery": [
            {
                "slug": "loader",
                "name": "Loader",
                "category": "machinery",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 40,
                "usage": "Load sand and aggregates into trucks",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "concrete_mixer",
                "name": "Concrete Mixer",
                "category": "machinery",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 28,
                "usage": "Batch mortar for blockwork",
                "typical_count": {"min": 1, "max": 2},
            },
        ],
    },
    "slab_concreting": {
        "keywords": [
            "cast the slab",
            "slab concreting",
            "pour the slab",
            "raft foundation",
            "ground beam concreting",
            "deck pour",
        ],
        "fallback_tokens": ["slab", "deck", "concrete pour"],
        "roles": [
            {
                "slug": "formwork_carpenter",
                "english": "Formwork Carpenter",
                "sinhala": "කළුමැටි කඩන්කර",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 8000, "max": 11500},
                "responsibilities": "Fabricate and strike shuttering for slabs, beams and columns",
                "typical_count": {"min": 3, "max": 6},
            },
            {
                "slug": "steel_fixer",
                "english": "Steel Fixer / Bar Bender",
                "sinhala": "ස්ටීල් ෆික්සර්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7500, "max": 11000},
                "responsibilities": "Tie reinforcement mats, install chairs and spacers",
                "typical_count": {"min": 4, "max": 8},
            },
            {
                "slug": "concrete_pump_operator",
                "english": "Concrete Pump Operator",
                "sinhala": "කොන්ක්‍රීට් පම්ප් මෙහෙයවන්නා",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 9000, "max": 13000},
                "responsibilities": "Operate pump and boom, coordinate pours with batching plant",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "concrete_vibrator_operator",
                "english": "Concrete Vibrator Operator",
                "sinhala": "කම්පන මෙහෙයවන්නා",
                "skill_level": "semi-skilled",
                "daily_rate_lkr": {"min": 6000, "max": 8000},
                "responsibilities": "Consolidate concrete using needle vibrators and monitor honeycombing",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "batcher_helper",
                "english": "Batcher Helper / Mixer Crew",
                "sinhala": "මෝටර් මික්සර් කණ්ඩායම",
                "skill_level": "semi-skilled",
                "daily_rate_lkr": {"min": 5000, "max": 7000},
                "responsibilities": "Feed mixers, control water/cement ratios, support QA cube making",
                "typical_count": {"min": 2, "max": 5},
            },
            {
                "slug": "general_labourer_slab",
                "english": "General Labourer (Slab)",
                "sinhala": "කම්කරු",
                "skill_level": "unskilled",
                "daily_rate_lkr": {"min": 3500, "max": 5000},
                "responsibilities": "Carry rebar, vibrators, hoses, assist in screeding and curing",
                "typical_count": {"min": 6, "max": 12},
            },
            {
                "slug": "site_engineer_slab",
                "english": "Site Engineer / QA",
                "sinhala": "සයිට් ඉංජිනේරු",
                "skill_level": "professional",
                "daily_rate_lkr": {"min": 18000, "max": 35000},
                "responsibilities": "Approve pour sequence, check slump, sign off cube samples",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "safety_officer_slab",
                "english": "Safety Officer",
                "sinhala": "සුරක්ෂිතතා නිලධාරී",
                "skill_level": "professional",
                "daily_rate_lkr": {"min": 12000, "max": 20000},
                "responsibilities": "Monitor working at height, pump hose handling and night lighting",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
        "vehicles": [
            {
                "slug": "concrete_mixer_truck",
                "name": "Concrete Mixer Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 60,
                "usage": "Transit mixers supplying the pour",
                "typical_count": {"min": 2, "max": 6},
            },
            {
                "slug": "tipper_truck",
                "name": "Tipper Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 45,
                "usage": "Back-haul aggregates and remove debris",
                "typical_count": {"min": 1, "max": 3},
            },
            {
                "slug": "lowbed",
                "name": "Low-bed Trailer",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 58,
                "usage": "Mobilise table forms and pump",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
        "machinery": [
            {
                "slug": "concrete_pump",
                "name": "Concrete Pump",
                "category": "machinery",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 65,
                "usage": "Place concrete on deck pours",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "concrete_mixer",
                "name": "Concrete Mixer",
                "category": "machinery",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 28,
                "usage": "Stand-by mixer / onsite batching",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "vibrator",
                "name": "Concrete Vibrator",
                "category": "machinery",
                "fuel_type": "Petrol",
                "fuel_liters_per_shift": 8,
                "usage": "Consolidate concrete",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "formwork_system",
                "name": "Formwork System",
                "category": "machinery",
                "fuel_type": "None",
                "fuel_liters_per_shift": 0,
                "usage": "Table forms and props",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
    },
    "interior_fitout": {
        "keywords": [
            "interior design",
            "fit-out",
            "fit out",
            "fitout",
            "gypsum ceiling",
            "drywall partition",
            "acoustic ceiling",
            "paint the interior",
            "timber flooring",
            "office renovation",
        ],
        "fallback_tokens": ["interior", "ceiling", "drywall", "fitout"],
        "roles": [
            {
                "slug": "interior_designer",
                "english": "Interior Designer / Coordinator",
                "sinhala": "අභ්‍යන්තර සැලසුම්කරු",
                "skill_level": "professional",
                "daily_rate_lkr": {"min": 20000, "max": 40000},
                "responsibilities": "Interpret client mood boards, issue finishes schedule, coordinate suppliers",
                "typical_count": {"min": 1, "max": 1},
            },
            {
                "slug": "drywall_carpenter",
                "english": "Drywall Carpenter",
                "sinhala": "ඩ්‍රයිවෝල් කාර්පෙන්ටර්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7000, "max": 10000},
                "responsibilities": "Install metal studs, gypsum boards, reveals and trims",
                "typical_count": {"min": 3, "max": 6},
            },
            {
                "slug": "ceiling_installer",
                "english": "Ceiling Installer",
                "sinhala": "සිලින් පල්ලිගන්නා",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7000, "max": 9500},
                "responsibilities": "Hang acoustic tiles, gypsum ceilings, set suspension grids",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "finishing_carpenter",
                "english": "Finishing Carpenter",
                "sinhala": "අලංකාර කාර්පෙන්ටර්",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7500, "max": 11000},
                "responsibilities": "Fabricate panelling, doors, skirtings, built-in furniture",
                "typical_count": {"min": 2, "max": 5},
            },
            {
                "slug": "painter",
                "english": "Painter / Finisher",
                "sinhala": "පින්තාරු",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 6500, "max": 9000},
                "responsibilities": "Surface prep, primer, top coats, decorative finishes",
                "typical_count": {"min": 3, "max": 6},
            },
            {
                "slug": "tiler",
                "english": "Tiler",
                "sinhala": "ටයිල් කම්කරුවා",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7000, "max": 10000},
                "responsibilities": "Lay porcelain/ceramic tiles, grouting, level checks",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "electrician_fitout",
                "english": "Electrician (Fit-out)",
                "sinhala": "විදුලි කම්කරුවා",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7500, "max": 11000},
                "responsibilities": "Run conduit, lighting layouts, smart controls for interiors",
                "typical_count": {"min": 1, "max": 3},
            },
            {
                "slug": "plumber_fitout",
                "english": "Plumber (Sanitary / Pantry)",
                "sinhala": "දිය නළ කම්කරුවා",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 7500, "max": 10500},
                "responsibilities": "Install sanitary fixtures, pantry sinks, concealed piping",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "hvac_technician",
                "english": "HVAC Technician",
                "sinhala": "එච්වීඒසි කාර්මික",
                "skill_level": "skilled",
                "daily_rate_lkr": {"min": 9000, "max": 13000},
                "responsibilities": "Install ducting, VRF cassettes, test air balancing",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "interior_helper",
                "english": "Interior Helper / Runner",
                "sinhala": "අභ්‍යන්තර උපකාරක",
                "skill_level": "unskilled",
                "daily_rate_lkr": {"min": 4000, "max": 5500},
                "responsibilities": "Material handling, masking, site cleaning between trades",
                "typical_count": {"min": 4, "max": 8},
            },
        ],
        "vehicles": [
            {
                "slug": "panel_van",
                "name": "Panel Van",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 16,
                "usage": "Deliver finishes, fixtures and joinery",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "pickup_truck",
                "name": "Pickup Truck",
                "category": "vehicle",
                "fuel_type": "Diesel",
                "fuel_liters_per_shift": 18,
                "usage": "Site supervision and light cargo",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
        "machinery": [
            {
                "slug": "scissor_lift",
                "name": "Scissor Lift",
                "category": "machinery",
                "fuel_type": "Electric",
                "fuel_liters_per_shift": 0,
                "usage": "Elevated work for ceilings and lighting",
                "typical_count": {"min": 1, "max": 2},
            },
            {
                "slug": "power_tools",
                "name": "Power Tools",
                "category": "machinery",
                "fuel_type": "Electric",
                "fuel_liters_per_shift": 0,
                "usage": "Hand tools, drills, sanders",
                "typical_count": {"min": 2, "max": 4},
            },
            {
                "slug": "vacuum_sander",
                "name": "Vacuum Sander",
                "category": "machinery",
                "fuel_type": "Electric",
                "fuel_liters_per_shift": 0,
                "usage": "Dust-free finishing of panels and floors",
                "typical_count": {"min": 1, "max": 1},
            },
        ],
    },
}
